Module2 task1
htmlacademy-vue/217599-pizza-1 pull request #2
Opened 2021-07-04 20:17 UTC by Shirokuiu

2021-07-06 21:30 UTC, vas11yev1work reviewed
В целом все хорошо, жду правки по комментариям.
Были места в которых недочеты были идентичны с теми, что я уже описывал ранее в других файлах, поэтому я не стал дублировать.

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/modules/builder/components/TheBuilder.vue
> +        @onIngredientDrop="updateIngredientsPrice($event)"
В таких вызовах, когда у нас в аргумент функции передается $event, его можно не писать
То есть, например `@onDoughChange="updateCurrentDough($event)"` будет равносильно `@onDoughChange="updateCurrentDough"`

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppRadioButton.vue
> +    },
Критерий Б3. Нужно задать либо required: true либо default
Для массивов default можно задать вот так 
```
props: {
  arr: {
    type: Array,
    default: () => []
  }
}
```
Ссылка на ишью: https://github.com/vuejs/vue/issues/1032#issuecomment-120212888

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppCounter.vue
> +    },
Критерий Б3. Нужно задать либо required: true либо default
Для массивов default можно задать вот так 
```
props: {
  arr: {
    type: Array,
    default: () => []
  }
}
```
Ссылка на ишью: https://github.com/vuejs/vue/issues/1032#issuecomment-120212888

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppWidget.vue
> +    },
Критерий Б3. Нужно задать либо required: true либо default
Для массивов default можно задать вот так 
```
props: {
  arr: {
    type: Array,
    default: () => []
  }
}
```
Ссылка на ишью: https://github.com/vuejs/vue/issues/1032#issuecomment-120212888

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppRadioButton.vue
> +    },
И кстати, я так понимаю этот пропс служит для передачи классов на корневой тег компонента. В таком случае делать пропс не обязательно, на компонент ты можешь повесить обычный class и все будет работать как надо

Ссылка на документацию: https://ru.vuejs.org/v2/guide/class-and-style.html#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%D0%B8

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppWidget.vue
> +    },
Вот в таком случае уже более уместно использование пропса для передачи классов

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +          @onRadioChange="onSauceChange($event)"
У нас есть директива v-model, которую мы можем привязать к какому-то инпуту. RadioButton не исключение, то есть обычному radio мы можем задать директиву v-model. Но эту директиву мы так же можем задать и компоненту, настроив внутри компонента нужные свойства: принимающее значение и emit.

Ссылка на документацию: https://ru.vuejs.org/v2/guide/components-custom-events.html#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v-model-%D1%83-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/modules/builder/components/TheBuilder.vue
> +    },
Такой подход во Vue не очень правильный. То есть по сути ты считаешь что-то, когда изменилось какое-то значение. Для такого у нас есть computed свойства.

То есть вместо того, чтобы задать в `data` свойство `totalPrice`, ты можешь создать computed-свойство `totalPrice` и оно будет автоматически обновляться при изменении переменных, от которых оно зависит и не понадобится при каждом действии вызывать функцию `updateTotalPrice`

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          :value="value"
Здесь ты в value передаешь объект. В итоге он превращается в строку и в шаблоне получается `value="[object Object]"`

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          :checked="isChecked"
Тут немного неправильный подход (и тут есть еще баг в том, что в пропсах не изменяется поле isChecked, если выбрать другой элемент)

Как вообще работать с радиокнопками во Vue. У нас есть директива `v-model` для двустороннего связывания. Соответственно мы можем создать в data какую-то переменную, которую привяжем ко множеству радиокнопок с одним `name`. При выборе у нас данная переменная будет изменяться. Соответственно привязав переменную через `v-model` мы избавляемся сразу от 3-х полей `:value`, `:checked` и `@change`

Отправлять `$emit` мы можем в `watch` при изменении этой же переменной, которую мы создадим в `data`

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/normalizeDoughs.js
> +      isChecked: index === 0,
Соответственно, исходя из комментария в BuilderDoughSelector мы можем избавится от поля isChecked

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/normalizeSauces.js
> +    isChecked: index === 0,
Аналогично в normalizeDoughs

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/normalizeSizes.js
> +    isChecked: index === 1,
Аналогично в normalizeDoughs

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppRadioButton.vue
> +    />
У нас есть директива v-model, которую мы можем привязать к какому-то инпуту. RadioButton не исключение, то есть обычному radio мы можем задать директиву v-model. Но эту директиву мы так же можем задать и компоненту, настроив внутри компонента нужные свойства: принимающее значение и emit.

Ссылка на документацию: https://ru.vuejs.org/v2/guide/components-custom-events.html#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v-model-%D1%83-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppDrop.vue
> +        );
Сюда можно передать уже созданную переменную payload

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/modules/builder/components/BuilderPizzaViewItem.vue
> +        :class-mods="['counter--orange', 'ingridients__counter']"
Ошибка ingredients

2021-07-06 21:30 UTC, vas11yev1work commented on src/frontend/src/common/components/AppCounter.vue
> +        value: undefined,
По-моему нет никакого смысла использовать `value: undefined`. Но если все же нужно передавать пустое значение, то лучше использовать `null`

2021-07-09 06:22 UTC, Shirokuiu commented on src/frontend/src/modules/builder/components/BuilderPizzaViewItem.vue
> +        :class-mods="['counter--orange', 'ingridients__counter']"
в стилях такой же класс
![Снимок экрана 2021-07-09 в 09 21 52](https://user-images.githubusercontent.com/20666315/125032784-21ff6000-e097-11eb-96b2-f69c086724d5.png)

2021-07-15 18:25 UTC, Djaler commented on src/frontend/src/modules/builder/components/TheBuilder.vue
> +      return (
в расчете стоимости должен учитываться размер

2021-07-15 18:26 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +        <div class="pizza pizza--foundation--big-tomato">
в этом блоке должно отражаться состояние пиццы (в зависимости от настроек теста, соуса, ингридиентов)

2021-07-15 18:32 UTC, Djaler commented on src/frontend/src/common/components/AppCounter.vue
> +      type="button"
кнопки должны отключаться когда нельзя уменьшить/увеличить количество ингредиентов

2021-07-15 18:34 UTC, Djaler requested changes
Отсутствует часть функционала по ТЗ.
Часть правок, оставленных на предыдущем ревью, не исправлена

2021-07-15 20:18 UTC, Shirokuiu commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +        <div class="pizza pizza--foundation--big-tomato">
Согласно пунктам ТЗ этого раздела, реализовывать данный функционал не нужно
![Снимок экрана 2021-07-15 в 23 18 36](https://user-images.githubusercontent.com/20666315/125852091-300e484a-2b27-4a54-9794-5cceacc43c3f.png)

2021-07-15 20:21 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +        <div class="pizza pizza--foundation--big-tomato">
Частично - только про пункт 3.7, не так ли?
Про пункт 3.2 этого не сказано, а именно он описывает эту логику

2021-07-15 20:23 UTC, Shirokuiu commented on src/frontend/src/common/components/AppCounter.vue
> +      type="button"
Опять же, в рамках этого модуля этот функционал реализовывать не нужно
![Снимок экрана 2021-07-15 в 23 22 28](https://user-images.githubusercontent.com/20666315/125852541-9b49e4c1-b502-4749-8938-594340785fe8.png)

2021-07-15 20:23 UTC, Shirokuiu commented
Какая именно часть ТЗ указанного в этом модуле не реализована ?
И какие именно правки по прошлым замечаниям не исправлены ?
P.S. Если про v-model, то мне пока не удобно ее реализовывать. Критерии академии меня в этом не ограничивают. Это было утверждено с предыдущим наставником

2021-07-15 20:25 UTC, Shirokuiu commented
По итогу мне надо добавить в расчет учитывание цены при выборе размера пиццы. Если так, то пушу этот фикс. Если нет, то тогда жду пояснений

2021-07-15 20:25 UTC, Djaler commented on src/frontend/src/common/components/AppCounter.vue
> +      type="button"
3.2.3 Изменение ингредиентов
В случае если количество ингредиента на пицце равно 3-м, кнопка + становится неактивной, также отключается возможность переноса ингредиента на пиццу.

В случае если количество ингредиента на пицце равно 0, кнопка - становится неактивной.

2021-07-15 20:27 UTC, Djaler commented
> Если про v-model, то мне пока не удобно ее реализовывать. Критерии академии меня в этом не ограничивают. Это было утверждено с предыдущим наставником
Ну, я же об этом не в курсе, в обсуждениях на гитхабе этого нет)

2021-07-15 20:29 UTC, Shirokuiu commented
> Ну, я же об этом не в курсе, в обсуждениях на гитхабе этого нет)
Согласен) Просто наставник сказал что его не будет и поэтому редиректнул мрчик

2021-07-16 11:04 UTC, Djaler commented
Можно мерджить, думаю

2021-07-16 12:14 UTC, merged

2021-07-16 12:14 UTC, Shirokuiu commented
Done